version: '2'
services:
    videorental-app:
        image: videorental
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://videorental-postgresql:5432/videoRental
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    videorental-postgresql:
        extends:
            file: postgresql.yml
            service: videorental-postgresql
